
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - app_name
  - service_name
  - installation_root_folder
  - service_file_path
  - alt_service_filepath

- name: gather installed services
  service_facts:

- name: stop the service
  service:
    name: "{{ service_name }}"
    state: stopped
    enabled: no
  when: "service_name in services"
  become: yes

- name: remove the service
  file:
    path: "{{ service_file_path }}"
    state: absent
  become: yes

- name: remove alternative service file path
  file:
    path: "{{ alt_service_filepath }}"
    state: absent
  become: yes

- name: remove tracking files
  file: 
    path: "{{ installation_root_folder }}/{{ item }}"
    state: absent
  with_items:
    - "{{ app_name }}-previous"
    - "{{ app_name }}-current"
  become: yes

- name: find app versions
  find:
    path: "{{ installation_root_folder }}"
    pattern: "{{ app_name }}-*"
    file_type: directory
  register: application_versions
  become: yes

- name: remove application versions
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ application_versions.files }}"
  become: yes

- name: remove data folder
  file:
    path: "{{ data_folder }}"
    state: absent
  become: yes

- name: remove logs folder
  file:
    path: "{{ logs_folder }}"
    state: absent
  become: yes
